### PR TITLE
Reminder feature

### PR DESCRIPTION
**Pull request by panzerox123**
This script can be included in .bashrc and it would open up every new terminal with all the tasks due for that day and the next.

### CODE REVIEW

**Comment by thescriptninja** [comment]
Hello @panzerox123! Thanks for your pull request.
I am, in fact, running the script from the terminal after adding the executable path to the .bashrc file. Need to add it to the README.md file. :smile:  

Coming to your PR, it is basically adding sections for tasks due today and tomorrow.
I would prefer that the file `script.py` is converted to an executable and all the functions are imported to it from the other modules.  
Can you please instead modify the `display_todos` function in the `script.py` to display "Due TODAY" or "Due TOMORROW" or, alternatively:
```
Due TODAY:
Task 1
Task 2
--------------------------------
Due TOMORROW
Task 1
Task 3
--------------------------------
other tasks
```
Try to stick to the current format of displaying the todos.
Comment down here if you have any doubt or need help.

**Comment by panzerox123** [comment]
Sure let me give it a try :)

**Comment by thescriptninja** [comment]
Hi @panzerox123. Are you interested in pursuing this further or should I close this PR?

**Comment by panzerox123** [comment]
I'm so sorry. Have exams going on. Ill positively finish it tomorrow :)

**Comment by thescriptninja** [comment]
Hey it is not a problem at all. Take your time and prioritize exams plz (even I have mine going on) :wink: I just wanted to know if you are still interested.

**Pull request closed without merging**
