### PR TITLE
Adds --disable_quotes options

### LINKED ISSUE #17: Add --quotes option
Currently, the app serves random quotes selected from `quotes.txt`. However, there should be an option to disable quotes.

### PR DESCRIPTION
**Pull request by janish1999**
Fixes #17 
Added options to Enable/Disable quotes

### CODE REVIEW

**Comment by thescriptninja** [comment]
Hi @janish1999 . Apparaently some xml files have crept up in this PR. Please remove them.

**Comment by thescriptninja** [comment]
I would also appreciate if you made the changes in separate commits, each commit describing smaller sub-changes, as is the recommended way. Thanks!

**Comment by thescriptninja** [comment]
I would suggest creating a new PR once #18 is merged. Otherwise, we may face unnecessary merge conflicts. Sorry for the inconvenience.
Also, please don't edit the Pipfile manually in anyway.

**Comment by janish1999** [comment]
Yeah sure.
I'll create a new pull request after #18 is merged

**Comment by thescriptninja** [comment]
Thanks a lot! :+1:

**Pull request closed without merging**
